/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Me
         * @description 204 when the cookie is valid; 401 otherwise — enforced entirely by
         *     the `require_session` dependency, so a valid request has nothing left
         *     to do.
         */
        get: operations["read_me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session
         * @description Body `{token}`; on match sets the session cookie and returns 204;
         *     401 otherwise (spec Section 7.2). The token arrives in the POST body,
         *     never a query string, so it never reaches a request line or a log
         *     (spec Section 7.5).
         */
        post: operations["create_session_api_auth_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tree */
        get: operations["get_tree_api_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentKind
         * @enum {string}
         */
        AgentKind: "codex" | "claude" | "antigravity";
        /**
         * CheckoutKind
         * @enum {string}
         */
        CheckoutKind: "primary" | "worktree";
        /** CheckoutNode */
        CheckoutNode: {
            /** Branch */
            branch: string | null;
            /** Detached */
            detached: boolean;
            /** Error */
            error: string | null;
            /** Host Branch */
            host_branch: boolean;
            /** Id */
            id: string;
            kind: components["schemas"]["CheckoutKind"];
            /** Merged */
            merged: boolean;
            /** Missing */
            missing: boolean;
            /** Path */
            path: string;
            /** Reason */
            reason: string | null;
            /** Sessions */
            sessions: components["schemas"]["SessionNode"][];
            status: components["schemas"]["WorkspaceStatus"];
            /** Workspace */
            workspace: string;
        };
        /**
         * ErrorDetail
         * @description The shape of every non-2xx JSON body this contract documents:
         *     FastAPI's own `{"detail": ...}` envelope, `detail` always a plain
         *     string here — an `HTTPException`'s `detail`, whether explicit
         *     (`/api/tree`'s 503, `snapshot.registry_error`, already sanitized by
         *     Task 2) or the default reason phrase FastAPI fills in when a route
         *     raises without one (`/api/tree`'s 401, `/api/auth/session`'s 401/403,
         *     `/api/auth/me`'s 401). Fix round 1 (Important 2): documented so
         *     `openapi-typescript`/`openapi-fetch` (spec Section 9.1) generate a
         *     typed error shape instead of leaving these routes' non-2xx responses
         *     undocumented.
         */
        ErrorDetail: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Version */
            version: string;
        };
        /** ProjectNode */
        ProjectNode: {
            /** Checkouts */
            checkouts: components["schemas"]["CheckoutNode"][];
            /** Error */
            error: string | null;
            /** Id */
            id: string;
            /** Integration Branch */
            integration_branch: string;
            /** Name */
            name: string;
            /** Primary Path */
            primary_path: string;
            /** Unregistered */
            unregistered: components["schemas"]["UnregisteredNode"][];
        };
        /** SessionNode */
        SessionNode: {
            agent: components["schemas"]["AgentKind"];
            /** Cwd */
            cwd: string;
            /** Ended At */
            ended_at: string | null;
            /** Id */
            id: string;
            /** Last Healthy At */
            last_healthy_at: string | null;
            /** Started At */
            started_at: string | null;
            state: components["schemas"]["SessionState"];
            /** Terminal Id */
            terminal_id: string | null;
            /** Title */
            title: string;
        };
        /** SessionRequest */
        SessionRequest: {
            /** Token */
            token: string;
        };
        /**
         * SessionState
         * @enum {string}
         */
        SessionState: "starting" | "running" | "detached" | "suspended" | "exited_resumable" | "completed" | "recovery_required" | "failed";
        /** TreeResponse */
        TreeResponse: {
            /** Projects */
            projects: components["schemas"]["ProjectNode"][];
            /**
             * Read At
             * Format: date-time
             */
            read_at: string;
        };
        /** UnregisteredNode */
        UnregisteredNode: {
            /** Branch */
            branch: string | null;
            /** Detached */
            detached: boolean;
            /** Missing */
            missing: boolean;
            /** Path */
            path: string;
            /** Prunable */
            prunable: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkspaceStatus
         * @description Estado de um workspace visto por `discover`, sem muta-lo.
         * @enum {string}
         */
        WorkspaceStatus: "ready" | "absent" | "unavailable";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid session cookie. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    create_session_api_auth_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token did not match. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Origin header missing or not the daemon's own (or, with --dev, the Vite origin). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_tree_api_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeResponse"];
                };
            };
            /** @description Missing or invalid session cookie. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Registry read failed; `detail` is the sanitized reason, verbatim. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
}
