#!/usr/bin/env node
// Synchronizes repository skills from the single source of truth (.claude/skills)
// to platform mirrors (.agents/skills and .codex/skills).
//
// Source of truth: .claude/skills/<name>/SKILL.md
// Generated mirrors:
//   - .agents/skills/<name>/SKILL.md   (Google Antigravity)
//   - .codex/skills/<name>/SKILL.md    (OpenAI Codex)
//
// Usage:
//   node scripts/sync-skills.mjs            Updates mirrors
//   node scripts/sync-skills.mjs --check    Checks for drift
//   node scripts/sync-skills.mjs --prune    Removes orphan mirrors

import { readFileSync, writeFileSync, readdirSync, mkdirSync, rmSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')

const SOURCE = '.claude/skills'
const MIRRORS = ['.agents/skills', '.codex/skills']
const VENDOR = new Set(['graphify'])

const CHECK = process.argv.includes('--check')
const PRUNE = process.argv.includes('--prune')

const BANNER_LINES = [
  '<!-- GENERATED by scripts/sync-skills.mjs from .claude/skills/ — DO NOT EDIT.',
  '     Edit the skill at its source and run: node scripts/sync-skills.mjs -->',
]

function render(source) {
  const NL = source.includes('\r\n') ? '\r\n' : '\n'
  const banner = BANNER_LINES.join(NL)
  const fm = /^---\r?\n[\s\S]*?\r?\n---\r?\n/.exec(source)
  if (!fm) return `${banner}${NL}${NL}${source}`
  const head = source.slice(0, fm[0].length)
  const body = source.slice(fm[0].length)
  return `${head}${NL}${banner}${NL}${NL}${body.replace(/^(\r?\n)+/, '')}`
}

const sameContent = (a, b) =>
  a !== null && a.replace(/\r\n/g, '\n') === b.replace(/\r\n/g, '\n')

function listSkills(dir) {
  const full = resolve(ROOT, dir)
  if (!existsSync(full)) return []
  return readdirSync(full, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !VENDOR.has(e.name))
    .map((e) => e.name)
    .sort()
}

const skills = listSkills(SOURCE)

if (skills.length === 0) {
  console.error(`[sync-skills] No skills found in ${SOURCE}`)
  process.exit(1)
}

let changes = 0
let drift = 0

for (const mirror of MIRRORS) {
  for (const skill of skills) {
    const srcPath = resolve(ROOT, SOURCE, skill, 'SKILL.md')
    if (!existsSync(srcPath)) {
      console.error(`[sync-skills] ${SOURCE}/${skill}: SKILL.md missing — skipping`)
      process.exitCode = 1
      continue
    }
    const expected = render(readFileSync(srcPath, 'utf8'))
    const dstDir = resolve(ROOT, mirror, skill)
    const dstPath = join(dstDir, 'SKILL.md')
    const current = existsSync(dstPath) ? readFileSync(dstPath, 'utf8') : null

    if (sameContent(current, expected)) continue

    if (CHECK) {
      console.error(`[sync-skills] DRIFT: ${mirror}/${skill}/SKILL.md`)
      drift++
      continue
    }
    mkdirSync(dstDir, { recursive: true })
    writeFileSync(dstPath, expected)
    console.log(`[sync-skills] ${mirror}/${skill}/SKILL.md -> updated`)
    changes++
  }

  for (const stale of listSkills(mirror).filter((s) => !skills.includes(s))) {
    if (CHECK) {
      console.error(`[sync-skills] ORPHAN: ${mirror}/${stale}/ does not exist in ${SOURCE}`)
      drift++
      continue
    }
    if (!PRUNE) {
      console.error(
        `[sync-skills] ORPHAN: ${mirror}/${stale}/ does not exist in ${SOURCE}. ` +
          `Move it to ${SOURCE}/ or remove with: node scripts/sync-skills.mjs --prune`
      )
      continue
    }
    rmSync(resolve(ROOT, mirror, stale), { recursive: true, force: true })
    console.log(`[sync-skills] ${mirror}/${stale}/ -> removed (orphan)`)
    changes++
  }
}

if (CHECK) {
  if (drift > 0) {
    console.error(`[sync-skills] ${drift} drift(s) detected. Run: node scripts/sync-skills.mjs`)
    process.exit(1)
  }
  console.log(`[sync-skills] ${skills.length} skill(s) synchronized across ${MIRRORS.length} mirrors.`)
} else if (changes === 0 && !process.exitCode) {
  console.log(`[sync-skills] ${skills.length} skill(s) already in sync. Nothing to do.`)
} else if (changes > 0) {
  console.log(`[sync-skills] Updated ${changes} file(s) from ${SOURCE}.`)
}
